### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by UnknownNull** [Estem01/NightPvP#16]
i test it but notwork for me!?

**Comment by Estem01** [comment]
@UnknownNull I'll try to see if I can solve it

**Comment by Estem01** [comment]
@UnknownNull Test it now and see if it's working 😁

**Comment by UnknownNull** [comment]
No... In my opinion, test it yourself first and if the plugin works without any problems, publish it as Release.I tested it on fake players @Estem01

**Comment by Estem01** [comment]
@UnknownNull I don't have a device to test so I published without a test to solve the bugs :/ But I'm already close to solving it, I don't know if it's because of the world class, it wasn't anymore, if not, I'll make some changes

**Comment by UnknownNull** [comment]
Remover config and test it

**Comment by UnknownNull** [comment]
Brother, in my opinion, look at the new library because you are moving the plugin in api3 style...

**Comment by Estem01** [comment]
I'll take a closer look, I'm now starting to work with plugin api 4 and some of them look similar to api 3 and 2 :/,

**Comment by Estem01** [comment]
now it works
